version: '3'
services:
  postgres:
    build: .
    hostname: dw-analytics
    container_name: dw-analytics
    ports:
      - "3307:5432"
    volumes:
      - dwanalytics:/var/lib/postgresql/data 
    networks:
      - analytics-network

networks: 
  analytics-network:
    name: analytics-network
    driver: bridge

volumes:
  dwanalytics: