version: '3'
services:
  postgres:
    build: .
    hostname: dw-analytics
    container_name: dw-analytics
    ports:
      - "3307:5432"
    volumes:
      - dwanalytics:/var/lib/postgresql/data 
    networks:
      - analytics-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

networks: 
  analytics-network:
    name: analytics-network
    driver: bridge

volumes:
  dwanalytics: